services:
  backend:
    build: .
    container_name: annotation_backend
    ports:
      - "5000:5000"
    volumes:
      - ./Simple-Human-Loop/img:/app/Simple-Human-Loop/img
      - ./static/asterix:/app/static/asterix
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/annotation_db
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    container_name: annotation_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: annotation_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: